items = {"BFSword", "ChainVest", "GiantsBelt", "NeedlesslyLargeRod", "NegatronCloak", "RecurveBow",
         "SparringGloves", "Spatula", "TearoftheGoddess", "ArcanistEmblem", "ArchangelsStaff", "AssassinEmblem",
         "BansheesClaw", "Bloodthirster", "BlueBuff", "BrambleVest", "ChaliceofPower","ChallengerEmblem","ChemtechEmblem",
         "Deathblade","DebonairEmblem","DragonsClaw","EdgeofNight","FrozenHeart","GargoyleStoneplate","GiantSlayer","GuinsoosRageblade",
         "HandofJustice","HextechEmblem","HextechGunblade","InfinityEdge","IonicSpark","JewledGauntlet","LastWhisper","LocketoftheIronSolari",
         "Morellonomicon","MutantEmblem","Quicksilver","RabadonsDeathcap","RapidFirecannon","Redemption","RunaansHurricane","ShroudofStillness",
         "SpearofShojin","StatikkShiv","StrikerEmblem","SunfireCape","TacticiansCrown","ThiefsGloves","TitansResolve","WarmogsArmor",
         "ZekesHerald","Zephyr","ZZRotPortal","AnimaVisage","DeathsDefiance","EternalWinter","GoldCollector","InfinityForce","Manazane",
         "ObsidianCleaver","RaduinsSanctum","RocketPropelledFist","ZhonyasParadox","BodyguardEmblem","BruiserEmblem","ClockworkEmblem",
         "EnforcerEmblem","InnovatorEmblem","MercenaryEmblem","ScholarEmblem","ScrapEmblem","SniperEmblem","SocialiteEmblem","SyndicateEmblem",
         "BansheesSilence","BlessedBloodthirster","BlueBlessing","BrinkofDawn","ChaliceofCharity","CovalentSpark","DemonSlayer","DragonsWill",
         "DvarapalaStoneplate", "EternalWhisper", "FistofFairness","FrozenHeartOfGold","GlamorousGauntlet","GuinsoosReckoning","HextechLifeblade",
         "LocketofTargonPrime","LuminousDeathblade","Mistral","MoreMoreellonomicon","Quickestsilver","RabadonsAscendedDeathcap","RadiantRedemption","RapidLightcannon",
         "RascalsGloves","RosethornVest","RunaansTempest","ShroudofReverance","SpearofHirana","StatikkFavor","SunlightCape","TitansVow","UrfAngelsStaff","WarmogsPride",
         "ZekesHarmony", "ZenithEdge", "ZzRotsInvitation"} 

champions = {'Ahri', 'Alistar', 'Ashe', 'Blitzcrank', 'Brand', 'Braum', 'Caitlyn', 'Camille', "Cho'Gath", 'Corki', 'Darius', 'Draven',
             'Ekko', 'Ezreal', 'Galio', 'Gangplank', 'Gnar', 'Illaoi', 'Irelia', 'Jarvan IV', 'Jayce', 'Jhin', 'Jinx', "Kai'Sa",
             'Kassadin', "Kha'Zix", 'Leona', 'Lucian', 'Lulu', 'Malzahar', 'Miss Fortune', 'Morgana', 'Nocturne', 'Orianna', 'Poppy',
             'Quinn', "Rek'Sai", 'Renata Glasc', 'Sejuani', 'Senna', 'Seraphine', 'Silco', 'Singed', 'Sivir', 'Swain', 'Syndra', 'Tahm Kench',
             'Talon', 'Tryndamere', 'Twitch', 'Veigar', 'Vex', 'Vi', 'Viktor', 'Warwick', 'Zac', 'Zeri', 'Ziggs', 'Zilean', 'Zyra'}


champion_data = {
    "Ahri": {"Gold": 4, "Board Size": 1},
    "Alistar": {"Gold": 4, "Board Size": 2},
    "Ashe": {"Gold": 2, "Board Size": 1},
    "Blitzcrank": {"Gold": 2, "Board Size": 1},
    "Brand": {"Gold": 1, "Board Size": 1},
    "Braum": {"Gold": 4, "Board Size": 1},
    "Caitlyn": {"Gold": 1, "Board Size": 1},
    "Camille": {"Gold": 1, "Board Size": 1},
    "Cho'Gath": {"Gold": 3, "Board Size": 2},
    "Corki": {"Gold": 2, "Board Size": 1},
    "Darius": {"Gold": 1, "Board Size": 1},
    "Draven": {"Gold": 4, "Board Size": 1},
    "Ekko": {"Gold": 3, "Board Size": 1},
    "Ezreal": {"Gold": 1, "Board Size": 1},
    "Galio": {"Gold": 1, "Board Size": 2},
    "Gangplank": {"Gold": 3, "Board Size": 1},
    "Gnar": {"Gold": 3, "Board Size": 1},
    "Illaoi": {"Gold": 1, "Board Size": 1},
    "Irelia": {"Gold": 4, "Board Size": 1},
    "Jarvan IV": {"Gold": 1, "Board Size": 1},
    "Jayce": {"Gold": 5, "Board Size": 1},
    "Jhin": {"Gold": 4, "Board Size": 1},
    "Jinx": {"Gold": 5, "Board Size": 1},
    "Kai'Sa": {"Gold": 5, "Board Size": 1},
    "Kassadin": {"Gold": 1, "Board Size": 1},
    "Kha'Zix": {"Gold": 4, "Board Size": 1},
    "Leona": {"Gold": 3, "Board Size": 1},
    "Lucian": {"Gold": 3, "Board Size": 1},
    "Lulu": {"Gold": 2, "Board Size": 1},
    "Malzahar": {"Gold": 3, "Board Size": 1},
    "Miss Fortune": {"Gold": 3, "Board Size": 1},
    "Morgana": {"Gold": 3, "Board Size": 1},
    "Nocturne": {"Gold": 1, "Board Size": 1},
    "Orianna": {"Gold": 4, "Board Size": 1},
    "Poppy": {"Gold": 1, "Board Size": 1},
    "Quinn": {"Gold": 2, "Board Size": 1},
    "Rek'Sai": {"Gold": 2, "Board Size": 1},
    "Renata Glasc": {"Gold": 4, "Board Size": 1},
    "Sejuani": {"Gold": 2, "Board Size": 1},
    "Senna": {"Gold": 3, "Board Size": 1},
    "Seraphine": {"Gold": 4, "Board Size": 1},
    "Silco": {"Gold": 5, "Board Size": 1},
    "Singed": {"Gold": 1, "Board Size": 1},
    "Sivir": {"Gold": 4, "Board Size": 1},
    "Swain": {"Gold": 2, "Board Size": 1},
    "Syndra": {"Gold": 2, "Board Size": 1},
    "Tahm Kench": {"Gold": 5, "Board Size": 1},
    "Talon": {"Gold": 2, "Board Size": 1},
    "Tryndamere": {"Gold": 3, "Board Size": 1},
    "Twitch": {"Gold": 1, "Board Size": 1},
    "Veigar": {"Gold": 5, "Board Size": 1},
    "Vex": {"Gold": 3, "Board Size": 1},
    "Vi": {"Gold": 4, "Board Size": 1},
    "Viktor": {"Gold": 5, "Board Size": 1},
    "Warwick": {"Gold": 2, "Board Size": 1},
    "Zac": {"Gold": 3, "Board Size": 1},
    "Zeri": {"Gold": 5, "Board Size": 1},
    "Ziggs": {"Gold": 1, "Board Size": 1},
    "Zilean": {"Gold": 2, "Board Size": 1},
    "Zyra": {"Gold": 2, "Board Size": 1}
    }

rounds = {"1-1", "1-2", "1-3", "1-4",
          "2-1", "2-2", "2-3", "2-4", "2-5", "2-6", "2-7",
          "3-1", "3-2", "3-3", "3-4", "3-5", "3-6", "3-7",
          "4-1", "4-2", "4-3", "4-4", "4-5", "4-6", "4-7",
          "5-1", "5-2", "5-3", "5-4", "5-5", "5-6", "5-7",
          "6-1", "6-2", "6-3", "6-4", "6-5", "6-6", "6-7",
          "7-1", "7-2", "7-3", "7-4", "7-5", "7-6", "7-7"}

carousel_rounds = {"1-1", "2-4", "3-4", "4-4", "5-4", "6-4", "7-4"}

pve_round = {"1-2", "1-3", "1-4", "2-7", "3-7", "4-7", "5-7", "6-7", "7-7"}

pvp_round = {"2-1", "2-2", "2-3", "2-5", "2-6",
             "3-1", "3-2", "3-3", "3-5", "3-6",
             "4-1", "4-2", "4-3", "4-5", "4-6",
             "5-1", "5-2", "5-3", "5-5", "5-6",
             "6-1", "6-2", "6-3", "6-5", "6-6",
             "7-1", "7-2", "7-3", "7-5", "7-6"}

pickup_round = {"2-1", "3-1", "4-1", "5-1", "6-1", "7-1"}

augment_rounds = {"1-4", "3-3", "4-6"}

item_placement_rounds = {"2-2", "3-2", "4-2", "5-2", "6-2", "7-2", "2-5", "3-5", "4-5", "5-5", "6-5", "7-5"}

final_comp_round = "4-5"

full_items = {"ArcanistEmblem": ("NeedlesslyLargeRod", "Spatula"),
              "ArchangelsStaff": ("NeedlesslyLargeRod", "TearoftheGoddess"),
              "AssassinEmblem": ("SparringGloves", "Spatula"),
              "BansheesClaw": ("GiantsBelt", "SparringGloves"),
              "Bloodthirster": ("BFSword", "NegatronCloak"),
              "BlueBuff": ("TearoftheGoddess", "TearoftheGoddess"),
              "BrambleVest": ("ChainVest", "ChainVest"),
              "ChaliceofPower": ("NegatronCloak", "TearoftheGoddess"),
              "ChallengerEmblem": ("RecurveBow", "Spatula"),
              "ChemtechEmblem": ("GiantsBelt", "Spatula"),
              "Deathblade": ("BFSword", "BFSword"),
              "DebonairEmblem": ("ChainVest", "Spatula"),
              "DragonsClaw": ("NegatronCloak", "NegatronCloak"),
              "EdgeofNight": ("BFSword", "ChainVest"),
              "FrozenHeart": ("ChainVest", "TearoftheGoddess"),
              "GargoyleStoneplate": ("ChainVest", "NegatronCloak"),
              "GiantSlayer": ("BFSword", "RecurveBow"),
              "GuinsoosRageblade": ("NeedlesslyLargeRod", "RecurveBow"),
              "HandofJustice": ("SparringGloves", "TearoftheGoddess"),
              "HextechEmblem": ("TearoftheGoddess", "Spatula"),
              "HextechGunblade": ("BFSword", "NeedlesslyLargeRod"),
              "InfinityEdge": ("BFSword", "SparringGloves"),
              "IonicSpark": ("NeedlesslyLargeRod", "NegatronCloak"),
              "JeweledGauntlet": ("NeedlesslyLargeRod", "SparringGloves"),
              "LastWhisper": ("RecurveBow", "SparringGloves"),
              "LocketoftheIronSolari": ("ChainVest", "NeedlesslyLargeRod"),
              "Morellonomicon": ("GiantsBelt", "NeedlesslyLargeRod"),
              "MutantEmblem": ("NegatronCloak", "Spatula"),
              "Quicksilver": ("NegatronCloak", "SparringGloves"),
              "RabadonsDeathcap": ("NeedlesslyLargeRod", "NeedlesslyLargeRod"),
              "RapidFirecannon": ("RecurveBow", "RecurveBow"),
              "Redemption": ("GiantsBelt", "TearoftheGoddess"),
              "RunaansHurricane": ("NegatronCloak", "RecurveBow"),
              "ShroudofStillness": ("ChainVest", "SparringGloves"),
              "SpearofShojin": ("BFSword", "TearoftheGoddess"),
              "StatikkShiv": ("RecurveBow", "TearoftheGoddess"),
              "StrikerEmblem": ("BFSword", "Spatula"),
              "SunfireCape": ("ChainVest", "GiantsBelt"),
              "TacticiansCrown": ("Spatula", "Spatula"),
              "ThiefsGloves": ("SparringGloves", "SparringGloves"),
              "TitansResolve": ("ChainVest", "RecurveBow"),
              "WarmogsArmor": ("GiantsBelt", "GiantsBelt"),
              "ZekesHerald": ("BFSword", "GiantsBelt"),
              "Zephyr": ("GiantsBelt", "NegatronCloak"),
              "ZzRotPortal": ("GiantsBelt", "RecurveBow")
              }

