"""
Contains static item
"""

BASIC_ITEMS: set[str] = {
    "BFSword",
    "ChainVest",
    "GiantsBelt",
    "NeedlesslyLargeRod",
    "NegatronCloak",
    "RecurveBow",
    "SparringGloves",
    "Spatula",
    "TearoftheGoddess",
}

COMBINED_ITEMS: set[str] = {
    "BilgewaterEmblem",
    "ChallengerEmblem",
    "IoniaEmblem",
    "JuggernautEmblem",
    "NoxusEmblem",
    "ShurimaEmblem",
    "SorcererEmblem",
    "VanquisherEmblem",
    "AdaptiveHelm",
    "ArchangelsStaff",
    "Bloodthirster",
    "BlueBuff",
    "BrambleVest",
    "Crownguard",
    "Deathblade",
    "DragonsClaw",
    "EdgeofNight",
    "Evenshroud",
    "GargoyleStoneplate",
    "GiantSlayer",
    "Guardbreaker",
    "GuinsoosRageblade",
    "HandofJustice",
    "HextechGunblade",
    "InfinityEdge",
    "IonicSpark",
    "JeweledGauntlet",
    "LastWhisper",
    "Morellonomicon",
    "NashorsTooth",
    "NightHarvester",
    "ProtectorsVow",
    "Quicksilver",
    "RabadonsDeathcap",
    "RapidFirecannon",
    "Redemption",
    "RunaansHurricane",
    "SpearofShojin",
    "StatikkShiv",
    "SteraksGage",
    "SunfireCape",
    "TacticiansCrown",
    "ThiefsGloves",
    "TitansResolve",
    "WarmogsArmor"
}

SUPPORT_ITEM: set[str] = {
    "AegisoftheLegion",
    "BansheesVeil",
    "ChaliceofPower",
    "CrestofCinders",
    "LocketoftheIronSolari",
    "NeedlesslyBigGem",
    "ObsidianCleaver",
    "RanduinsOmen",
    "ShroudofStillness",
    "VirtueoftheMartyr",
    "ZekesHerald",
    "Zephyr",
    "ZzRotPortal"
}

NON_CRAFTABLE_ITEMS: set[str] = {
    "BastionEmblem",
    "BruiserEmblem",
    "DeadeyeEmblem",
    "FreljordEmblem",
    "GunnerEmblem",
    "InvokerEmblem",
    "PiltoverEmblem",
    "RogueEmblem",
    "StrategistEmblem",
    "TargonEmblem",
    "VoidEmblem",
    "ZaunEmblem"
}

ORNN_ITEMS: set[str] = {
    "AnimaVisage",
    "BlacksmithsGloves",
    "DeathfireGrasp",
    "DeathsDefiance",
    "EternalWinter",
    "GoldCollector",
    "GoldmancersStaff",
    "Hullcrusher",
    "InfinityForce",
    "MogulsMail",
    "Muramana",
    "Rocket-PropelledFist",
    "SnipersFocus",
    "TrickstersGlass",
    "ZhonyasParadox"
    }

ITEMS: set[str] = BASIC_ITEMS.union(COMBINED_ITEMS).union(SUPPORT_ITEM).union(NON_CRAFTABLE_ITEMS).union(ORNN_ITEMS)

ROUNDS: set[str] = {
    "1-1",
    "1-2",
    "1-3",
    "1-4",
    "2-1",
    "2-2",
    "2-3",
    "2-4",
    "2-5",
    "2-6",
    "2-7",
    "3-1",
    "3-2",
    "3-3",
    "3-4",
    "3-5",
    "3-6",
    "3-7",
    "4-1",
    "4-2",
    "4-3",
    "4-4",
    "4-5",
    "4-6",
    "4-7",
    "5-1",
    "5-2",
    "5-3",
    "5-4",
    "5-5",
    "5-6",
    "5-7",
    "6-1",
    "6-2",
    "6-3",
    "6-4",
    "6-5",
    "6-6",
    "6-7",
    "7-1",
    "7-2",
    "7-3",
    "7-4",
    "7-5",
    "7-6",
    "7-7"
}

PORTAL_ROUND: set[str] = {"1-1"}

SECOND_ROUND: set[str] = {"1-2"}

CAROUSEL_ROUND: set[str] = {"2-4", "3-4", "4-4", "5-4", "6-4", "7-4"}

PVE_ROUND: set[str] = {"1-3", "1-4", "2-7", "3-7", "4-7", "5-7", "6-7", "7-7"}

PVP_ROUND: set[str] = {
    "2-1",
    "2-2",
    "2-3",
    "2-5",
    "2-6",
    "3-1",
    "3-2",
    "3-3",
    "3-5",
    "3-6",
    "4-1",
    "4-2",
    "4-3",
    "4-5",
    "4-6",
    "5-1",
    "5-2",
    "5-3",
    "5-5",
    "5-6",
    "6-1",
    "6-2",
    "6-3",
    "6-5",
    "6-6",
    "7-1",
    "7-2",
    "7-3",
    "7-5",
    "7-6"
}

PICKUP_ROUNDS: set[str] = {"2-1", "3-1", "4-1", "5-1", "6-1", "7-1"}

ANVIL_ROUNDS: set[str] = {
    "2-1",
    "2-5",
    "3-1",
    "3-5",
    "4-1",
    "4-5",
    "5-1",
    "5-5",
    "6-1",
    "6-5",
    "7-1",
    "7-5"
}

AUGMENT_ROUNDS: set[str] = {"2-1", "3-2", "4-2"}

REGION_ROUNDS: set[str] = {"2-5", "4-5"}

ITEM_PLACEMENT_ROUNDS: set[str] = {
    "2-1",
    "2-5",
    "2-7",
    "3-2",
    "3-5",
    "4-2",
    "4-5",
    "5-2",
    "5-5",
    "5-7",
    "6-2",
    "6-5",
    "7-2",
    "7-5",
    "7-7"
}

FINAL_COMP_ROUND = "4-5"

FULL_ITEMS = {
    "BilgewaterEmblem":("Spatula","NegatronCloak"),
    "ChallengerEmblem":("Spatula","RecurveBow"),
    "IoniaEmblem":("Spatula","BFSword"),
    "JuggernautEmblem":("Spatula","ChainVest"),
    "NoxusEmblem":("Spatula","GiantsBelt"),
    "ShurimaEmblem":("Spatula","NeedlesslyLargeRod"),
    "SorcererEmblem":("Spatula","TearoftheGoddess"),
    "VanquisherEmblem":("Spatula","SparringGloves"),
    "AdaptiveHelm":("NegatronCloak","TearoftheGoddess"),
    "ArchangelsStaff":("NeedlesslyLargeRod","TearoftheGoddess"),
    "Bloodthirster":("BFSword","NegatronCloak"),
    "BlueBuff":("TearoftheGoddess","TearoftheGoddess"),
    "BrambleVest":("ChainVest","ChainVest"),
    "Crownguard":("ChainVest","NeedlesslyLargeRod"),
    "Deathblade":("BFSword","BFSword"),
    "DragonsClaw":("NegatronCloak","NegatronCloak"),
    "EdgeofNight":("BFSword","ChainVest"),
    "Evenshroud":("GiantsBelt","NegatronCloak"),
    "GargoyleStoneplate":("ChainVest","NegatronCloak"),
    "GiantSlayer":("BFSword","RecurveBow"),
    "Guardbreaker":("GiantsBelt","SparringGloves"),
    "GuinsoosRageblade":("NeedlesslyLargeRod","RecurveBow"),
    "HandofJustice":("SparringGloves","TearoftheGoddess"),
    "HextechGunblade":("BFSword","NeedlesslyLargeRod"),
    "InfinityEdge":("BFSword","SparringGloves"),
    "IonicSpark":("NeedlesslyLargeRod","NegatronCloak"),
    "JeweledGauntlet":("NeedlesslyLargeRod","SparringGloves"),
    "LastWhisper":("RecurveBow","SparringGloves"),
    "Morellonomicon":("GiantsBelt","NeedlesslyLargeRod"),
    "NashorsTooth":("GiantsBelt","RecurveBow"),
    "NightHarvester":("ChainVest","SparringGloves"),
    "ProtectorsVow":("ChainVest","TearoftheGoddess"),
    "Quicksilver":("NegatronCloak","SparringGloves"),
    "RabadonsDeathcap":("NeedlesslyLargeRod","NeedlesslyLargeRod"),
    "RapidFirecannon":("RecurveBow","RecurveBow"),
    "Redemption":("GiantsBelt","TearoftheGoddess"),
    "RunaansHurricane":("NegatronCloak","RecurveBow"),
    "SpearofShojin":("BFSword","TearoftheGoddess"),
    "StatikkShiv":("RecurveBow","TearoftheGoddess"),
    "SteraksGage":("BFSword","GiantsBelt"),
    "SunfireCape":("ChainVest","GiantsBelt"),
    "TacticiansCrown":("Spatula","Spatula"),
    "ThiefsGloves":("SparringGloves","SparringGloves"),
    "TitansResolve":("ChainVest","RecurveBow"),
    "WarmogsArmor":("GiantsBelt","GiantsBelt")
}

# No logic for certain augments meaning the bot won't know what to do if they are included in here
# (Anything that changes gameplay or adds something to the bench).
AUGMENTS: list[str] = [
    "March of Progress",
    "Tons of Stats!",
    "Gifts from the Fallen",
    "Item Grab Bag II",
    "Know Your Enemy",
    "Red Buff",
    "Unified Resistance I",
    "Unified Resistance II",
    "Level Up!",
    "You Have My Bow",
    "Harmacist II",
    "You Have My Sword",
    "Harmacist I",
    "Matyr",
    "Jewled Lotus III",
    "Built Different III",
    "Cybernetic Leech I",
    "Final Ascension",
    "Long Distance Pals II",
    "Cybernetic Leech II",
    "Combat Caster",
    "Magic Wand",
    "Idealism",
    "Battle Ready III",
    "Item Grab Bag I",
    "Harmacist III",
    "Final Grab Bag II",
    "Healing Orbs I",
    "Return on Investment",
    "Contagion",
    "Tiny Titans",
    "Battle Ready II",
    "Risky Moves",
    "Shoplifting",
    "Last Stand",
    "Jewled Lotus II",
    "Money Money!",
    "Healing Orbs II",
    "Giant Grab Bag",
    "Cybernetic Leech III",
]

PORTALS: list[str] = [
    "Marus Omegnum",
    "Stillwater Hold",
    "Ecliptic Vaults",
    "Petricite Forest",
    "The Lavender Sea",
    "The University",
    "Jayce's Workshop",
    "Glasc Industries",
    "The Sump",
    "The Rupture",
]