items = {"BFSword", "ChainVest", "GiantsBelt", "NeedlesslyLargeRod", "NegatronCloak", "RecurveBow",
         "SparringGloves", "Spatula", "TearoftheGoddess", "AcademyEmblem", "ArcanistEmblem", "AssassinEmblem",
         "ChallengerEmblem", "ChemtechEmblem", "ImperialEmblem", "MutantEmblem", "SyndicateEmblem", "ArchangelsStaff",
         "BansheesClaw", "Bloodthirster", "BlueBuff", "BrambleVest", "ChaliceofPower", "Deathblade", "DragonsClaw",
         "FrozenHeart", "GargoyleStoneplate", "GiantSlayer", "GuardianAngel", "GuinsoosRageblade", "HandofJustice",
         "HextechGunblade", "InfinityEdge", "IonicSpark", "JeweledGauntlet", "LastWhisper", "LocketoftheIronSolari",
         "Morellonomicon", "Quicksilver", "RabadonsDeathcap", "RapidFirecannon", "Redemption", "RunaansHurricane",
         "ShroudofStillness", "SpearofShojin", "StatikkShiv", "SunfireCape", "TacticiansCrown", "ThiefsGloves",
         "TitansResolve", "WarmogsArmor", "ZekesHerald", "Zephyr", "ZzRotPortal", "Reforger"}

champions = {"Akali", "Blitzcrank", "Braum", "Caitlyn", "Camille", "Cho'Gath", "Darius", "Dr. Mundo", "Ekko", "Ezreal",
             "Fiora", "Galio", "Gangplank", "Garen", "Graves", "Heimerdinger", "Illaoi", "Janna", "Jayce", "Jhin",
             "Jinx", "Kaisa", "Kassadin", "Katarina", "Kog'Maw", "Leona", "Lissandra", "Lulu", "Lux", "Malzahar",
             "Miss Fortune", "Orianna", "Poppy", "Quinn", "Samira", "Seraphine", "Shaco", "Singed", "Sion", "Swain",
             "Tahm Kench", "Talon", "Taric", "Tristana", "Trundle", "Twisted Fate", "Twitch", "Urgot", "Veigar", "Vex",
             "Vi", "Viktor", "Warwick", "Yone", "Yuumi", "Zac", "Ziggs", "Zilean", "Zyra"}

champion_data = {
    "Akali": {"Gold": 5, "Board Size": 1},
    "Blitzcrank": {"Gold": 2, "Board Size": 1},
    "Braum": {"Gold": 4, "Board Size": 1},
    "Caitlyn": {"Gold": 1, "Board Size": 1},
    "Camille": {"Gold": 1, "Board Size": 1},
    "Cho'Gath": {"Gold": 3, "Board Size": 2},
    "Darius": {"Gold": 1, "Board Size": 1},
    "Dr Mundo": {"Gold": 4, "Board Size": 1},
    "Ekko": {"Gold": 3, "Board Size": 1},
    "Ezreal": {"Gold": 1, "Board Size": 1},
    "Fiora": {"Gold": 4, "Board Size": 1},
    "Galio": {"Gold": 5, "Board Size": 2},
    "Gangplank": {"Gold": 3, "Board Size": 1},
    "Garen": {"Gold": 1, "Board Size": 1},
    "Graves": {"Gold": 1, "Board Size": 1},
    "Heimerdinger": {"Gold": 3, "Board Size": 1},
    "Illaoi": {"Gold": 1, "Board Size": 1},
    "Janna": {"Gold": 4, "Board Size": 1},
    "Jayce": {"Gold": 5, "Board Size": 1},
    "Jhin": {"Gold": 4, "Board Size": 1},
    "Jinx": {"Gold": 5, "Board Size": 1},
    "Kai'Sa": {"Gold": 5, "Board Size": 1},
    "Kassadin": {"Gold": 1, "Board Size": 1},
    "Katarina": {"Gold": 2, "Board Size": 1},
    "Kog'Maw": {"Gold": 2, "Board Size": 1},
    "Leona": {"Gold": 3, "Board Size": 1},
    "Lissandra": {"Gold": 3, "Board Size": 1},
    "Lulu": {"Gold": 2, "Board Size": 1},
    "Lux": {"Gold": 4, "Board Size": 1},
    "Malzahar": {"Gold": 3, "Board Size": 1},
    "Miss Fortune": {"Gold": 3, "Board Size": 1},
    "Orianna": {"Gold": 4, "Board Size": 1},
    "Poppy": {"Gold": 1, "Board Size": 1},
    "Quinn": {"Gold": 2, "Board Size": 1},
    "Samira": {"Gold": 3, "Board Size": 1},
    "Seraphine": {"Gold": 4, "Board Size": 1},
    "Shaco": {"Gold": 3, "Board Size": 1},
    "Singed": {"Gold": 1, "Board Size": 1},
    "Sion": {"Gold": 4, "Board Size": 2},
    "Swain": {"Gold": 2, "Board Size": 1},
    "Tahm Kench": {"Gold": 5, "Board Size": 1},
    "Talon": {"Gold": 2, "Board Size": 1},
    "Taric": {"Gold": 3, "Board Size": 1},
    "Tristana": {"Gold": 2, "Board Size": 1},
    "Trundle": {"Gold": 2, "Board Size": 1},
    "Twisted Fate": {"Gold": 1, "Board Size": 1},
    "Twitch": {"Gold": 1, "Board Size": 1},
    "Urgot": {"Gold": 4, "Board Size": 1},
    "Veigar": {"Gold": 5, "Board Size": 1},
    "Vex": {"Gold": 3, "Board Size": 1},
    "Vi": {"Gold": 2, "Board Size": 1},
    "Viktor": {"Gold": 5, "Board Size": 1},
    "Warwick": {"Gold": 2, "Board Size": 1},
    "Yone": {"Gold": 4, "Board Size": 1},
    "Yuumi": {"Gold": 5, "Board Size": 1},
    "Zac": {"Gold": 3, "Board Size": 1},
    "Ziggs": {"Gold": 1, "Board Size": 1},
    "Zilean": {"Gold": 2, "Board Size": 1},
    "Zyra": {"Gold": 2, "Board Size": 1}, }

rounds = {"1-1", "1-2", "1-3", "1-4",
          "2-1", "2-2", "2-3", "2-4", "2-5", "2-6", "2-7",
          "3-1", "3-2", "3-3", "3-4", "3-5", "3-6", "3-7",
          "4-1", "4-2", "4-3", "4-4", "4-5", "4-6", "4-7",
          "5-1", "5-2", "5-3", "5-4", "5-5", "5-6", "5-7",
          "6-1", "6-2", "6-3", "6-4", "6-5", "6-6", "6-7",
          "7-1", "7-2", "7-3", "7-4", "7-5", "7-6", "7-7"}

carousel_rounds = {"1-1", "2-4", "3-4", "4-4", "5-4", "6-4", "7-4"}

pve_round = {"1-2", "1-3", "1-4", "2-7", "3-7", "4-7", "5-7", "6-7", "7-7"}

pvp_round = {"2-1", "2-2", "2-3", "2-5", "2-6",
             "3-1", "3-2", "3-3", "3-5", "3-6",
             "4-1", "4-2", "4-3", "4-5", "4-6",
             "5-1", "5-2", "5-3", "5-5", "5-6",
             "6-1", "6-2", "6-3", "6-5", "6-6",
             "7-1", "7-2", "7-3", "7-5", "7-6"}

pickup_round = {"2-1", "3-1", "4-1", "5-1", "6-1", "7-1"}

augment_rounds = {"1-4", "3-3", "4-6"}

item_placement_rounds = {"2-2", "3-2", "4-2", "5-2", "6-2", "7-2", "2-5", "3-5", "4-5", "5-5", "6-5", "7-5"}

final_comp_round = "4-5"

full_items = {"AcademyEmblem": ("Spatula", "TearoftheGoddess"),
              "ArcanistEmblem": ("NeedlesslyLargeRod", "Spatula"),
              "AssassinEmblem": ("SparringGloves", "Spatula"),
              "ChallengerEmblem": ("RecurveBow", "Spatula"),
              "ChemtechEmblem": ("GiantsBelt", "Spatula"),
              "ImperialEmblem": ("BFSword", "Spatula"),
              "MutantEmblem": ("NegatronCloak", "Spatula"),
              "SyndicateEmblem": ("ChainVest", "Spatula"),
              "ArchangelsStaff": ("NeedlesslyLargeRod", "TearoftheGoddess"),
              "BansheesClaw": ("GiantsBelt", "SparringGloves"),
              "Bloodthirster": ("BFSword", "NegatronCloak"),
              "BlueBuff": ("TearoftheGoddess", "TearoftheGoddess"),
              "BrambleVest": ("ChainVest", "ChainVest"),
              "ChaliceofPower": ("NegatronCloak", "TearoftheGoddess"),
              "Deathblade": ("BFSword", "BFSword"),
              "DragonsClaw": ("NegatronCloak", "NegatronCloak"),
              "FrozenHeart": ("ChainVest", "TearoftheGoddess"),
              "GargoyleStoneplate": ("ChainVest", "NegatronCloak"),
              "GiantSlayer": ("BFSword", "RecurveBow"),
              "GuardianAngel": ("BFSword", "ChainVest"),
              "GuinsoosRageblade": ("NeedlesslyLargeRod", "RecurveBow"),
              "HandofJustice": ("SparringGloves", "TearoftheGoddess"),
              "HextechGunblade": ("BFSword", "NeedlesslyLargeRod"),
              "InfinityEdge": ("BFSword", "SparringGloves"),
              "IonicSpark": ("NeedlesslyLargeRod", "NegatronCloak"),
              "JeweledGauntlet": ("NeedlesslyLargeRod", "SparringGloves"),
              "LastWhisper": ("RecurveBow", "SparringGloves"),
              "LocketoftheIronSolari": ("ChainVest", "NeedlesslyLargeRod"),
              "Morellonomicon": ("GiantsBelt", "NeedlesslyLargeRod"),
              "Quicksilver": ("NegatronCloak", "SparringGloves"),
              "RabadonsDeathcap": ("NeedlesslyLargeRod", "NeedlesslyLargeRod"),
              "RapidFirecannon": ("RecurveBow", "RecurveBow"),
              "Redemption": ("GiantsBelt", "TearoftheGoddess"),
              "RunaansHurricane": ("NegatronCloak", "RecurveBow"),
              "ShroudofStillness": ("ChainVest", "SparringGloves"),
              "SpearofShojin": ("BFSword", "TearoftheGoddess"),
              "StatikkShiv": ("RecurveBow", "TearoftheGoddess"),
              "SunfireCape": ("ChainVest", "GiantsBelt"),
              "TacticiansCrown": ("Spatula", "Spatula"),
              "ThiefsGloves": ("SparringGloves", "SparringGloves"),
              "TitansResolve": ("ChainVest", "RecurveBow"),
              "WarmogsArmor": ("GiantsBelt", "GiantsBelt"),
              "ZekesHerald": ("BFSword", "GiantsBelt"),
              "Zephyr": ("GiantsBelt", "NegatronCloak"),
              "ZzRotPortal": ("GiantsBelt", "RecurveBow")
              }
